@startuml

abstract class Personaje {
    - nombre: String
    - vida: int
    - danno: int
    - rangoMovimiento: int
    - rangoAtaque: int
    - habilidades: String
    + mover(casillaDestino: Casillas): void
    + atacar(objetivo: Enemigo): void
    + usarHabilidad(): void
}



 class CapitanOrion extends Personaje{
-tipo:String=”CapitanOrion”
-rangoMovimiento: 5
-rangoAtaque: 3
-danno: 2,4

+InspiracionGalactica():void

}
class Nova extends Personaje{
-tipo:String=”Nova”
-rangoMovimiento: 6
-rangoAtaque: 2
-danno: 1,3
+DesactivarTrampas():void
}
class Zorak extends Personaje {
-tipo:String=” Zorak”
-rangoMovimiento: 4
-rangoAtaque: 1
-danno: 4,6
+GolpeDeEnergia():void
}
class Lyra extends Personaje{
-tipo:String=”Lyra”
-rangoMovimiento: 5
-rangoAtaque: 4
-danno: 0
+CuracionCosmica():void
}
class Quasar extends Personaje{
-tipo:String=”Quasar”
-rangoMovimiento: 5
-rangoAtaque: 3
-danno: 1,2
+ReparacionRapida():void
}
class Eclipse extends Personaje{
-tipo:String=”Eclipse”
-rangoMovimiento: 7
-rangoAtaque: 2
-danno: 3,5
+AtaqueFurtivo():void
}
class Titan extends Personaje{
-tipo:String=”Titan”
-rangoMovimiento: 3
-rangoAtaque: 1
-danno: 2,3
+EscudoEnergia():void
}
class Stella extends Personaje{
-tipo:String=”Stella”
-rangoMovimiento: 5
-rangoAtaque: 6
-danno: 2,4
+ControlMental():void
}
class Vortex extends Personaje{
-tipo:String=”Vortex”
-rangoMovimiento: 5
-rangoAtaque: 5
-danno: 3,6
+TormentaCosmica():void
}
class Aurora extends Personaje{
-tipo:String=”Aurora”
-rangoMovimiento: 6
-rangoAtaque: 0
-danno: 0
+Negociacion():void
}
    class Blaze extends Personaje{
-tipo:String=”Blaze”
-rangoMovimiento: 4
-rangoAtaque: 2
-danno: 2,4
+DisparoExplosivo():void
}
class Luna extends Personaje{
-tipo:String=”Luna”
-rangoMovimiento: 4
-rangoAtaque: 2
-danno: 2,4
+InstintoDeCazadora():void
}
class Cygnus extends Personaje{
-tipo:String=”Cygnus”
+ManiobraEvasiva():void
}
class OrionJr extends Personaje{
-tipo:String=”OrionJr”
+PotencialDesbloqueado():void
}
class Nebula extends Personaje{
-tipo:String=”Nebula”
+SabiduriaAncestral():void
}
class Phobos extends Personaje{
-tipo:String=”Phobos”
+DisparoLetal():void
}
class Deimos extends Personaje{
-tipo:String=”Deimos”
+Infiltracion():void
}
class Solara extends Personaje{
-tipo:String=”Solara”
+MurallaDeLuz():void
}
class Comet extends Personaje{
-tipo:String=”Comet”
+GolpeRelampago():void
}
class Andromeda extends Personaje{
-tipo:String=”Andromeda”
+RitualEstelar():void
}



abstract class Enemigo  {
    - nombre: String
    - vida: int
    - danio: int
    - comportamientoIA: String
    + actuar(): void
}

class DroneCombate extends Enemigo{
    - tipo: String = "Drone"
    + escanear(): void
}

class ArañaCósmica  extends Enemigo{
    - tipo: String = "Araña"
    + lanzarRed(): void
}
class PiratasEspaciales extends Enemigo {
-tipo:String=”Piratas”
+robo():void
}
class GiganteDeLava extends Enemigo{
-tipo:String=”Gigante”
+erupción():void
}



class Tablero {
    - casillas: List<Casillas>
    - ancho: int
    - alto: int
    + generarNivel(nivel: int): void
    + obtenerCasillas(x: int, y: int): Casillas
}

class Casillas  {
    - x: int
    - y: int
    - tipo: String
    - contenido:
    - peligro: String
    + estaOcupada(): boolean ObjetoMagico
}

class ObjetoMagico {
    - nombre: String
    - efecto: String
    - rangoUso: int
    + usar(): void
}
class PocionCurativa extends ObjetoMagico{
-nombre: "Pocion Curativa"
-efecto: 3,5
-rangoUso: 1
+restauraVida()
}
class EscudoEnergia extends ObjetoMagico{
-nombre: "Escudo de energia"
-efecto: 4
-rangoUso: 1
+Absorbe()
}
class BombaPlasma extends ObjetoMagico{
-nombre: Bomba de BombaPlasma
-efecto: 3
-danno: int: 4,6
-rangoUso: 5
+Explota()
}

class Acertijo  {
    - descripcion: String
    - solucion: String
    + resolver(intento: String): boolean
}

class Juego {

    - enemigos: List<Enemigo>
    - tablero: Tablero
    - turnoActual: int
    + iniciarPartida(): void
    + finalizarTurno(): void
    + verificarVictoria(): boolean
}






Juego "1" *-- "1" Tablero: tiene

Juego "1" *-- "1..*" Enemigo: tiene
Juego "1" *-- "1..*" Acertijo: tiene
Juego "1" *-- "1..*" Personaje: tiene

Personaje -- Casillas: ocupa >
Enemigo -- Casillas: ocupa >
Tablero "1" *-- "1..*" Casillas: tiene
Juego "1" *-- "1..*" ObjetoMagico: tiene
@enduml
